# Generated by Django 5.0.1 on 2025-11-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
