# Generated by Django 5.0.1 on 2025-11-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_admin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_code',
            field=models.CharField(blank=True, help_text='Unique code for student registration (admins only)', max_length=20, null=True, unique=True),
        ),
    ]
