# Generated by Django 5.0.1 on 2025-11-18 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'domains',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_weeks', models.IntegerField(help_text='Number of weeks for the course')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domains', models.ManyToManyField(related_name='courses', to='students.domain')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('program', models.CharField(default='AI-Capsule', max_length=100)),
                ('next_milestone', models.CharField(default='Portfolio checkpoint', max_length=200)),
                ('domains_mastered', models.IntegerField(default=0)),
                ('total_domains', models.IntegerField(default=10)),
                ('overall_summary', models.TextField(blank=True)),
                ('trainer_feedback', models.TextField(blank=True)),
                ('program_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDomainScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.domain')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_scores', to='students.student')),
            ],
            options={
                'db_table': 'student_domain_scores',
                'unique_together': {('student', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='DomainWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('improvement_suggestion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='students.studentdomainscore')),
            ],
            options={
                'db_table': 'domain_weaknesses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strengths', to='students.studentdomainscore')),
            ],
            options={
                'db_table': 'domain_strengths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('week_start_date', models.DateField()),
                ('average_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to='students.student')),
            ],
            options={
                'db_table': 'weekly_progress',
                'ordering': ['week_number'],
                'unique_together': {('student', 'week_number')},
            },
        ),
    ]
