# Generated by Django 5.0.1 on 2025-11-19 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='announcements', to='students.course'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by', to='students.announcement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_announcements', to='students.student')),
            ],
            options={
                'db_table': 'announcement_reads',
                'unique_together': {('student', 'announcement')},
            },
        ),
    ]
