# Generated by Django 5.0.1 on 2025-11-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_announcement_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, help_text='When to stop showing this announcement', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='When to start showing this announcement', null=True),
        ),
    ]
