# Generated by Django 5.0.1 on 2025-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_project_grade_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='route_url',
            field=models.CharField(blank=True, help_text='Frontend route to navigate to', max_length=500, null=True),
        ),
    ]
