# Generated by Django 5.0.1 on 2025-11-20 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_notification_read_at_notification_route_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='domainstrength',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_strengths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainstrength',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('improved', 'Improved'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='domainstrength',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='domainweakness',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_weaknesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainweakness',
            name='status',
            field=models.CharField(choices=[('active', 'Needs Work'), ('improving', 'Improving'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='domainweakness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DomainChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('strength_added', 'Strength Added'), ('strength_improved', 'Strength Improved'), ('strength_archived', 'Strength Archived'), ('weakness_added', 'Weakness Added'), ('weakness_improving', 'Weakness Improving'), ('weakness_resolved', 'Weakness Resolved'), ('weakness_archived', 'Weakness Archived')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Additional context about the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_history', to='students.studentdomainscore')),
            ],
            options={
                'db_table': 'domain_change_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
