# Generated by Django 5.0.1 on 2025-11-20 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_domainstrength_added_by_domainstrength_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainstrength',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='domainstrength',
            name='status',
        ),
        migrations.RemoveField(
            model_name='domainstrength',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='domainweakness',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='domainweakness',
            name='status',
        ),
        migrations.RemoveField(
            model_name='domainweakness',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='domainweakness',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='domainweakness',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DomainHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('strength_added', 'Strength Added'), ('strength_improved', 'Strength Improved'), ('weakness_added', 'Weakness Added'), ('weakness_improved', 'Weakness Improved'), ('weakness_resolved', 'Weakness Resolved')], max_length=30)),
                ('skill_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status_badge', models.CharField(choices=[('new_strength', 'New Strength'), ('new_improvement', 'New Improvement'), ('improved', 'Improved'), ('resolved', 'Resolved')], default='new_strength', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_history_entries', to=settings.AUTH_USER_MODEL)),
                ('related_strength', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='students.domainstrength')),
                ('related_weakness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='students.domainweakness')),
                ('student_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='students.studentdomainscore')),
            ],
            options={
                'verbose_name_plural': 'Domain histories',
                'db_table': 'domain_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DomainChangeHistory',
        ),
    ]
