# Generated by Django 5.0.1 on 2025-11-20 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_domainstrength_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainweakness',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='domainstrength',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_strengths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainstrength',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, this strength was removed or resolved'),
        ),
        migrations.AddField(
            model_name='domainstrength',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainweakness',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_weaknesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domainweakness',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('improved', 'Improved'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='domainweakness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DomainProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('strength_added', 'Strength Added'), ('strength_removed', 'Strength Removed'), ('weakness_added', 'Weakness Added'), ('weakness_improved', 'Weakness Improved'), ('weakness_resolved', 'Weakness Resolved')], max_length=30)),
                ('item_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain_changes', to=settings.AUTH_USER_MODEL)),
                ('student_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='students.studentdomainscore')),
            ],
            options={
                'verbose_name_plural': 'Domain progress histories',
                'db_table': 'domain_progress_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DomainHistory',
        ),
    ]
